#!/bin/bash

session=${1:-default}
workdir=$HOME/Workspaces/$session
wsconfig=$workdir/workspace.yml

[ -d $workdir ] || mkdir -p $workdir

if [ -e $wsconfig ]; then
    for env in $(yq -r '.environment[]' $wsconfig); do
        env="${env/\$workdir/$workdir}"
        args="-e $env $args"
    done
fi

tmux -u new-session -AD -s $session -c $workdir $args
