#!/bin/bash

real_tmux=/usr/bin/tmux

_yq() {
    local scr="$1"
    local file="$2"
    yq -r "$scr" "$file" 2>/dev/null
}

tmux_here() {
    local workdir="$1"
    local name="${workdir##*/}-$$"
    local wsconfig="workspace.yml"

    local args=""
    local path=$PATH
    if [ -e $wsconfig ]; then
        for env in $(_yq '.environment[]' $wsconfig); do
            env="${env/\$workdir/$workdir}"
            args="-e $env $args"
        done
        for dir in $(_yq '.path[]' $wsconfig); do
            path="$dir:$path"
        done
    fi

    export PATH="$path"
    exec $real_tmux -u new-session -s $name -c $workdir $args
}

case $1 in
    here)
        tmux_here "$PWD"
        ;;
    *)
        exec $real_tmux "$@"
        ;;
esac
